### ISSUE TITLE
TypeError: unsupported operand type(s) for |: '_SpecialForm' and '_GenericAlias'

### ISSUE THREAD

**Issue by JuGuSm** [abhishekmj303/ytm2spt#11]
Hi,

When trying to import a YouTube Music playlist I get this error:

```
/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (2.2.2) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
Traceback (most recent call last):
  File "src/main.py", line 2, in <module>
    from spotify import Spotify
  File "/var/tmp/ytm2spt/src/spotify.py", line 51, in <module>
    class Spotify:
  File "/var/tmp/ytm2spt/src/spotify.py", line 229, in Spotify
    def _num_playlist_songs(self, playlist_id: str = "") -> Any | Literal[False] | None:
TypeError: unsupported operand type(s) for |: '_SpecialForm' and '_GenericAlias'
```

Also:

```
pip install -r requirements.txt
```
```
Requirement already satisfied: Levenshtein in /home/ubuntu/.local/lib/python3.8/site-packages (from -r requirements.txt (line 1)) (0.25.1)
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (from -r requirements.txt (line 2)) (2.22.0)
Requirement already satisfied: spotipy in /home/ubuntu/.local/lib/python3.8/site-packages (from -r requirements.txt (line 3)) (2.24.0)
Requirement already satisfied: thefuzz in /home/ubuntu/.local/lib/python3.8/site-packages (from -r requirements.txt (line 4)) (0.22.1)
Requirement already satisfied: ytmusicapi in /home/ubuntu/.local/lib/python3.8/site-packages (from -r requirements.txt (line 5)) (1.7.3)
Requirement already satisfied: rapidfuzz<4.0.0,>=3.8.0 in /home/ubuntu/.local/lib/python3.8/site-packages (from Levenshtein->-r requirements.txt (line 1)) (3.9.3)
Requirement already satisfied: redis>=3.5.3 in /home/ubuntu/.local/lib/python3.8/site-packages (from spotipy->-r requirements.txt (line 3)) (5.0.6)
Requirement already satisfied: urllib3>=1.26.0 in /home/ubuntu/.local/lib/python3.8/site-packages (from spotipy->-r requirements.txt (line 3)) (2.2.2)
Requirement already satisfied: async-timeout>=4.0.3; python_full_version < "3.11.3" in /home/ubuntu/.local/lib/python3.8/site-packages (from redis>=3.5.3->spotipy->-r requirements.txt (line 3)) (4.0.3)
```

```
lsb_release -a
```
```
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.6 LTS
Release:        20.04
Codename:       focal
```

**Comment by abhishekmj303** [comment]
> requests in /usr/lib/python3/dist-packages

I think the problem here is the `requests` library is imported from system installation which is done through `apt`.

Try installing requirements in a virtual environment:

**Installation:**
```shell
sudo apt update
sudo apt install python3-virtualenv
```

**Inside the project directory:**
Create virtualenv:
```
virtualenv venv
```
Activate:
```
source venv/bin/activate
```

Install dependencies:
```
pip install -r requirements.txt
```
Run the script as given in Usage.
**Note:** You need to activate virtualenv whenever you need to run the script.

**Comment by abhishekmj303** [comment]
Can you share the output of this:

```
source venv/bin/activate
echo $PYTHONPATH
pip install -r requirements.txt
```

It should have worked 🤔.

**Comment by JuGuSm** [comment]
```
source venv/bin/activate
```
```
-bash: venv/bin/activate: No such file or directory
```

**Comment by abhishekmj303** [comment]
Are you sure you are running this inside the project folder after creating the virtual environment?

**Comment by JuGuSm** [comment]
Oh sorry I didn't see the venv folder.
so the two first commands don't display any output.
The third one have an output but it's "already satisfied":

```
pip install -r requirements.txt
```
```
Requirement already satisfied: Levenshtein in ./venv/lib/python3.8/site-packages (from -r requirements.txt (line 1)) (0.25.1)
Requirement already satisfied: requests in ./venv/lib/python3.8/site-packages (from -r requirements.txt (line 2)) (2.32.3)
Requirement already satisfied: spotipy in ./venv/lib/python3.8/site-packages (from -r requirements.txt (line 3)) (2.24.0)
Requirement already satisfied: thefuzz in ./venv/lib/python3.8/site-packages (from -r requirements.txt (line 4)) (0.22.1)
Requirement already satisfied: ytmusicapi in ./venv/lib/python3.8/site-packages (from -r requirements.txt (line 5)) (1.7.3)
Requirement already satisfied: rapidfuzz<4.0.0,>=3.8.0 in ./venv/lib/python3.8/site-packages (from Levenshtein->-r requirements.txt (line 1)) (3.9.3)
Requirement already satisfied: urllib3<3,>=1.21.1 in ./venv/lib/python3.8/site-packages (from requests->-r requirements.txt (line 2)) (2.2.2)
Requirement already satisfied: charset-normalizer<4,>=2 in ./venv/lib/python3.8/site-packages (from requests->-r requirements.txt (line 2)) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in ./venv/lib/python3.8/site-packages (from requests->-r requirements.txt (line 2)) (3.7)
Requirement already satisfied: certifi>=2017.4.17 in ./venv/lib/python3.8/site-packages (from requests->-r requirements.txt (line 2)) (2024.6.2)
Requirement already satisfied: redis>=3.5.3 in ./venv/lib/python3.8/site-packages (from spotipy->-r requirements.txt (line 3)) (5.0.6)
Requirement already satisfied: async-timeout>=4.0.3; python_full_version < "3.11.3" in ./venv/lib/python3.8/site-packages (from redis>=3.5.3->spotipy->-r requirements.txt (line 3)) (4.0.3)
```

**Comment by JuGuSm** [comment]
Here is all the commands and all outputs I launched just after login:

```shell
$ cd /var/tmp/ytm2spt/
$ sudo apt update
Hit:1 http://nova.clouds.archive.ubuntu.com/ubuntu focal InRelease
Hit:2 http://nova.clouds.archive.ubuntu.com/ubuntu focal-updates InRelease
Hit:3 http://nova.clouds.archive.ubuntu.com/ubuntu focal-backports InRelease
Hit:4 http://security.ubuntu.com/ubuntu focal-security InRelease
Hit:5 http://ppa.launchpad.net/ansible/ansible/ubuntu focal InRelease
Reading package lists... Done
Building dependency tree
Reading state information... Done
All packages are up to date.
$ sudo apt install python3-virtualenv
Reading package lists... Done
Building dependency tree
Reading state information... Done
python3-virtualenv is already the newest version (20.0.17-1ubuntu0.4).
The following packages were automatically installed and are no longer required:
  ieee-data libpython2-stdlib libpython2.7-minimal libpython2.7-stdlib python2 python2-minimal python2.7 python2.7-minimal python3-argcomplete python3-dnspython python3-libcloud python3-lockfile
  python3-netaddr python3-selinux
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
$ virtualenv venv
created virtual environment CPython3.8.10.final.0-64 in 89ms
  creator CPython3Posix(dest=/var/tmp/ytm2spt/venv, clear=False, global=False)
  seeder FromAppData(download=False, pip=latest, setuptools=latest, wheel=latest, pkg_resources=latest, via=copy, app_data_dir=/home/ubuntu/.local/share/virtualenv/seed-app-data/v1.0.1.debian.1)
  activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator
$ source venv/bin/activate
$ echo $PYTHONPATH
$ PYTHONPATH=/usr/bin/python
$ echo $PYTHONPATH
/usr/bin/python
$ python --version
Python 3.8.10
$ pip install -r requirements.txt
Requirement already satisfied: Levenshtein in ./venv/lib/python3.8/site-packages (from -r requirements.txt (line 1)) (0.25.1)
Requirement already satisfied: requests in ./venv/lib/python3.8/site-packages (from -r requirements.txt (line 2)) (2.32.3)
Requirement already satisfied: spotipy in ./venv/lib/python3.8/site-packages (from -r requirements.txt (line 3)) (2.24.0)
Requirement already satisfied: thefuzz in ./venv/lib/python3.8/site-packages (from -r requirements.txt (line 4)) (0.22.1)
Requirement already satisfied: ytmusicapi in ./venv/lib/python3.8/site-packages (from -r requirements.txt (line 5)) (1.7.3)
Requirement already satisfied: rapidfuzz<4.0.0,>=3.8.0 in ./venv/lib/python3.8/site-packages (from Levenshtein->-r requirements.txt (line 1)) (3.9.3)
Requirement already satisfied: urllib3<3,>=1.21.1 in ./venv/lib/python3.8/site-packages (from requests->-r requirements.txt (line 2)) (2.2.2)
Requirement already satisfied: charset-normalizer<4,>=2 in ./venv/lib/python3.8/site-packages (from requests->-r requirements.txt (line 2)) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in ./venv/lib/python3.8/site-packages (from requests->-r requirements.txt (line 2)) (3.7)
Requirement already satisfied: certifi>=2017.4.17 in ./venv/lib/python3.8/site-packages (from requests->-r requirements.txt (line 2)) (2024.6.2)
Requirement already satisfied: redis>=3.5.3 in ./venv/lib/python3.8/site-packages (from spotipy->-r requirements.txt (line 3)) (5.0.6)
Requirement already satisfied: async-timeout>=4.0.3; python_full_version < "3.11.3" in ./venv/lib/python3.8/site-packages (from redis>=3.5.3->spotipy->-r requirements.txt (line 3)) (4.0.3)
$ python src/main.py -yt "https://music.youtube.com/playlist?list=$my_playlist_id"
Traceback (most recent call last):
  File "src/main.py", line 2, in <module>
    from spotify import Spotify
  File "/var/tmp/ytm2spt/src/spotify.py", line 51, in <module>
    class Spotify:
  File "/var/tmp/ytm2spt/src/spotify.py", line 229, in Spotify
    def _num_playlist_songs(self, playlist_id: str = "") -> Any | Literal[False] | None:
TypeError: unsupported operand type(s) for |: '_SpecialForm' and '_GenericAlias'
```

**Comment by abhishekmj303** [comment]
git pull and check if it's working

**Comment by JuGuSm** [comment]
It seems to work!
Thank you for your work and your quick support!

Do you have an estimation of the time it takes?
I launched the command 2 hours ago and it's still running (900 songs in the playlist)

**Comment by abhishekmj303** [comment]
I personally have not ran it on a huge playlist but if it's reflecting in Spotify then don't cancel it.

**Comment by JuGuSm** [comment]
No I don't see anything in Spotify.
I kill the process and ran it again on a smaller playlist (144 titles) but still running and nothing on Spotify.

**Comment by JuGuSm** [comment]
I only have the ID and the name of YouTube playlist.
Someting like this:
```shell
INFO - Youtube Playlist ID: XXX
INFO - Youtube Playlist Name: XXX
```

**Comment by abhishekmj303** [comment]
What is the error output when press control+c ?

**Comment by JuGuSm** [comment]
```
^CTraceback (most recent call last):
  File "src/main.py", line 149, in <module>
    spotify_id = get_spotify_playlist_id(spotify_arg, spotify_playlist_name)
  File "src/main.py", line 51, in get_spotify_playlist_id
    return sp.create_playlist(yt.get_playlist_title())
  File "/var/tmp/ytm2spt/src/spotify.py", line 91, in create_playlist
    "Authorization": f"Bearer {self.spotify.token}"
  File "/var/tmp/ytm2spt/src/spotify.py", line 42, in token
    return util.prompt_for_user_token(
  File "/var/tmp/ytm2spt/venv/lib/python3.8/site-packages/spotipy/util.py", line 97, in prompt_for_user_token
    code = sp_oauth.get_auth_response()
  File "/var/tmp/ytm2spt/venv/lib/python3.8/site-packages/spotipy/oauth2.py", line 480, in get_auth_response
    return self._get_auth_response_local_server(redirect_port)
  File "/var/tmp/ytm2spt/venv/lib/python3.8/site-packages/spotipy/oauth2.py", line 449, in _get_auth_response_local_server
    server.handle_request()
  File "/usr/lib/python3.8/socketserver.py", line 294, in handle_request
    ready = selector.select(timeout)
  File "/usr/lib/python3.8/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)
KeyboardInterrupt
```

**Comment by JuGuSm** [comment]
I can share my screen if you want:
https://us05web.zoom.us/j/89395100484?pwd=YnNlOG06FSoPSwaIP4X46mP4rjy5bx.1

**Comment by abhishekmj303** [comment]
No, it's not needed. I got where the problem is occurring through the logs.

I think you are running it in the ssh and the script is trying to open the browser to login to Spotify. It just hangs as it can't open anything.

Maybe run it in the local machine if possible.  I look and try to update the script when I get some free time.

Ps. You should never share your screen with any stranger on the internet for your own security.

**Comment by JuGuSm** [comment]
I'll try on a machine with a desktop.

Don't worry, I was sharing on a VM ;-)

Thank you for your help, really appreciated.

**Comment by JuGuSm** [comment]
Indeed, with a desktop environment it works much better :)
Again, thank you for your work AND for your help
